services:
  d10mongodb:
    image: mongo:5.0.1
    container_name: d10-mongodb
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - './db:/data/db'
    restart: always

  d10repo:
    image: mono:latest
    platform: linux/amd64
    container_name: d10-repo
    depends_on:
      d10mongodb:
        condition: service_healthy
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: bind
        source: ./client
        target: /deadline10/client
    environment:
      DEADLINE_VERSION: ${DEADLINE_VERSION}
    restart: no
    command: sh /opt/setup/setup_deadline.sh

  d10webservice:
    image: mono:latest
    platform: linux/amd64
    container_name: d10-webservice
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: curl -i http://0.0.0.0:8081 || exit 1
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 5s
    depends_on:
      d10repo:
        condition: service_completed_successfully
      d10mongodb:
        condition: service_healthy
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: bind
        source: ./client
        target: /deadline10/client
      - './install/deadline-webservice.ini:/var/lib/Thinkbox/Deadline10/deadline.ini'
    restart: always
    command: sh /opt/setup/run_webservice.sh

  d10rcs:
    image: mono:latest
    platform: linux/amd64
    container_name: d10-rcs
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: curl -i http://0.0.0.0:8080 || exit 1
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 5s
    depends_on:
      d10repo:
        condition: service_completed_successfully
      d10mongodb:
        condition: service_healthy
      d10webservice:
        condition: service_healthy
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: bind
        source: ./client
        target: /deadline10/client
      - './install/deadline-rcs.ini:/var/lib/Thinkbox/Deadline10/deadline.ini'
    restart: always
    command: sh /opt/setup/run_rcsservice.sh

networks:
  net:
    internal: false
    driver: bridge
    attachable: true
