services:
  d10mongodb:
    image: mongo:5.0.1
    container_name: d10-mongodb
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - './db:/data/db'
    restart: always

  d10repo:
    image: registry.recomblacksmith.com/deadline10-repo:${DEADLINE_VERSION}
    platform: linux/amd64
    container_name: d10-repo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      d10mongodb:
        condition: service_healthy
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: volume
        source: thinkbox
        target: /var/lib/Thinkbox
      - type: volume
        source: root-thinkbox
        target: /root/Thinkbox
    environment:
      DEADLINE_VERSION: ${DEADLINE_VERSION}
    restart: no
    command: sh /opt/setup/setup_deadline.sh

  d10webservice:
    image: registry.recomblacksmith.com/deadline10-webservice:${DEADLINE_VERSION}
    platform: linux/amd64
    container_name: d10-webservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: bash -c 'echo > /dev/tcp/0.0.0.0/8081' || exit 1
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 5s
    depends_on:
      d10mongodb:
        condition: service_healthy
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: bind
        source: ./client
        target: /deadline10/client
      - type: volume
        source: thinkbox
        target: /var/lib/Thinkbox
      - type: volume
        source: root-thinkbox
        target: /root/Thinkbox
    environment:
      DOTNET_EnableWriteXorExecute: "0"
    restart: always
    command: sh /opt/setup/run_webservice.sh

  d10rcs:
    image: registry.recomblacksmith.com/deadline10-rcs:${DEADLINE_VERSION}
    platform: linux/amd64
    container_name: d10-rcs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: bash -c 'echo > /dev/tcp/0.0.0.0/8080' || exit 1
      interval: 10s
      retries: 30
      start_period: 30s
      timeout: 5s
    depends_on:
      d10mongodb:
        condition: service_healthy
      d10webservice:
        condition: service_healthy
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: bind
        source: ./client
        target: /deadline10/client
      - type: volume
        source: thinkbox
        target: /var/lib/Thinkbox
      - type: volume
        source: root-thinkbox
        target: /root/Thinkbox
    environment:
      DOTNET_EnableWriteXorExecute: "0"
    restart: always
    command: sh /opt/setup/run_rcsservice.sh

networks:
  net:
    internal: false
    driver: bridge
    attachable: true

volumes:
  thinkbox:
  root-thinkbox:
