services:
  d10worker:
    image: registry.recomblacksmith.com/deadline10-worker:${DEADLINE_VERSION}
    platform: linux/amd64
    container_name: d10-worker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - net
    volumes:
      - type: bind
        source: ./install
        target: /opt/setup
      - type: bind
        source: ./repository
        target: /deadline10/repository
      - type: bind
        source: ./worker-client
        target: /deadline10/client
      - type: volume
        source: thinkbox
        target: /var/lib/Thinkbox
      - type: volume
        source: root-thinkbox
        target: /root/Thinkbox
    environment:
      DOTNET_EnableWriteXorExecute: "0"
      DEADLINE_VERSION: ${DEADLINE_VERSION}
    restart: on-failure
    command: sh /opt/setup/run_worker.sh

networks:
  net:
    name: deadline-container_net
    external: true

volumes:
  thinkbox:
    name: deadline-container_thinkbox
    external: true
  root-thinkbox:
    name: deadline-container_root-thinkbox
    external: true
